complexity:
  LongParameterList:
    allowedFunctionParameters: 8
    allowedConstructorParameters: 8
  TooManyFunctions:
    allowedFunctionsPerFile: 10
    allowedFunctionsPerClass: 10
    allowedFunctionsPerInterface: 10
    allowedFunctionsPerObject: 10
    allowedFunctionsPerEnum: 10

exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

style:
  ForbiddenComment:
    active: false
  MaxLineLength:
    maxLineLength: 130
  WildcardImport:
    excludeImports:
      - 'java.util.*'
      - 'org.mockito.kotlin.*'
      - 'kotlinx.coroutines.flow.*'
      - 'org.hamcrest.Matchers.*'
